### ISSUE TITLE
commit amend

### ISSUE THREAD

**Issue by kangwonlee** [kangwonlee/colab_template#1]
* instead of adding another commit for button & id handling, what about amend commit ?

**Comment by kangwonlee** [comment]
https://github.com/kangwonlee/colab_template/blob/7cf1afa366993da75d940b60bdcfb27e6632c62a/.github/workflows/conda_env_test.yml#L47-L51

**Comment by kangwonlee** [comment]
* https://github.com/stefanzweifel/git-auto-commit-action

``` yml
- uses: actions/checkout@master
  with:
    # Fetch the last 2 commits instead of just 1. (Fetching just 1 commit would overwrite the whole history)
    fetch-depth: 2

# Other steps in your workflow to trigger a changed file

- name: Get last commit message
  id: last-commit-message
  run: |
    echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

- uses: stefanzweifel/git-auto-commit-action@v4
  with:
    commit_message: ${{ steps.last-commit-message.outputs.msg }}
    commit_options: '--amend --no-edit'
    push_options: '--force'
    skip_fetch: true
```
